### ISSUE TITLE
Issue in CalFilterTpl with [id]

### ISSUE THREAD

**Issue by astrodaz** [jgulledge19/Church-Events-Calendar#10]
This is already logged, but the line of code does something odd..

[[~[[id]]? clear=`Y`]]

Issue 1: The is an asterisk missing from the [[id]] - it should read [[*id]]
Issue 2: What is this code supposed to do? I get a line of text output on the page:  "mypagename.php? clear=`Y`". If I comment out the line, the page appears to work OK, and the text disappears.

Thanks

**Comment by jgulledge19** [comment]
I will have this fixed in the next release.

The code is not necessary.
