### ISSUE TITLE
Login through web context

### ISSUE THREAD

**Issue by insomnix** [jgulledge19/Church-Events-Calendar#13]
I have 3 people that will be maintaining the calendar, I don't want to have anything to do with it beyond the set up. I do not want to give them access to the manager section of the site. How would I use Login to give them the privileges to use that section, or is it even possible? If not possible, that would be a nice addition.

**Comment by jgulledge19** [comment]
Fixed: https://github.com/jgulledge19/Church-Events-Calendar/commit/276b71469572a676bff25b794e48fc8212909653.

I will release an update shortly.

Thanks
