### ISSUE TITLE
issue using &calendarID call

### ISSUE THREAD

**Issue by nick2687** [jgulledge19/Church-Events-Calendar#18]
When making this call: [[!ChurchEventsCalendar?  &calendarID=`4`]]

The calendar seems to be ignoring the calendar id all together. 

categoryID is not functioning either

**Comment by hunterhig** [comment]
I have the same problem, &calendarID=4 not functioning. I don't need any calendars except ID 4, and would like to remove 1, 2, and 3.

I would also like to remove the "Choose a Calendar" dropdown and the iCal area, so the only things in that box are:
Choose a Category
Search
Sort

**Comment by jgulledge19** [comment]
@nick2687 actually it does work it is just not immediately evident. When you go to the page and saw any calendar view these are saved in the session.  So if you then change the &calendarID or &categoryID and refresh the page you will not see any difference.  But if you open up another browser (assuming you did not have a active session for the page) you will see your chosen calendarID and categoryID.  This is necessary for the page to remember your search info as you change views.  It is only confusing when you are setting up the page.

**Comment by jgulledge19** [comment]
@hunterhig copy the ChurchEvents_CalFilterTpl Chunk and rename it to something like my_CalFilterTplcal and remove the select form element and replace it with a hidden form element with your chosen ID.  Then call your snippet like so:
[[!ChurchEventsCalendar?
  &calFilterTpl=`my_CalFilterTplcal`
]]

**Comment by hunterhig** [comment]
Thanks very much for your reply - just want to be sure I understand
correctly:

in my chunk "my_CalFilterTplcal"

I change this:
<select name="church_calendar_id" class="displayBlock"
id="sel_church_calendar_id" >
                    [[+select_calendar]]
                </select>

to:
<hidden name="church_calendar_id" class="displayBlock" id="4" >
                    [[+select_calendar]]
                </hidden>

Is this what you suggested?

Thanks,
Wendy

On Fri, May 25, 2012 at 3:09 PM, jgulledge19 <
reply@reply.github.com
