### ISSUE TITLE
Unable to save an event.

### ISSUE THREAD

**Issue by peepslog** [jgulledge19/Church-Events-Calendar#2]
Error adding data line: 585 in file: /home/xxxxxxx/public_html/core/components/churchevents/model/churchevents/calendar/eventhooks.class.php

**Comment by jgulledge19** [comment]
Can you fill in some more info for me?

What version of Revo are you using and what version of ChurchEvents?  Can you go the Reports -> Error Log and post anything that says churchevents?

**Comment by peepslog** [comment]
My Revo version is 2.1.5-pl and my ChurchEvents version is 1.0.0-pl. My Repots -> Error log is absolutely empty with no error. 
I installed ChurchEvents 1.0.0-pl and selected the template. But when i try to submit an event after filling up the form, i get this error

" Error adding data line: 585 in file: /home/xxxx/public_html/core/components/churchevents/model/churchevents/calendar/eventhooks.class.php " .

Hope it can be figured out. This plugin is very nice. Thanks.

**Comment by jgulledge19** [comment]
Do you resolve this issue?  Can you tell me what it was?
