### ISSUE TITLE
Cannot see calendar events with Allow Requests set to no

### ISSUE THREAD

**Issue by astrodaz** [jgulledge19/Church-Events-Calendar#3]
With the system setting "Allow Requests" set to no, the events are not visible in the calendar, or as a list UNLESS I log into Manager, then they are visible again.

I need to be able to list/show events to non-manager users.

Thanks

**Comment by jgulledge19** [comment]
Can you fill in some more info for me?

What version of Revo are you using and what version of ChurchEvents?  Also are the events set to Approved?  I tested on Revo 2.1.5 and it seems to work fine for me.

**Comment by astrodaz** [comment]
OK my bad!!

The 'status' is not something I would need / use, so I took that placeholder out of my custom template, but I understand it's use now - I'll just default the selection!

Issue closed :)
