### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by nick2687** [jgulledge19/Church-Events-Calendar#4]
Ability to set the default calendar, category & calendar view displayed so that you can then hide the sorting options. This would allow for you to create a calendar for logged in users and one for the public without them being able to see the "members only" one.

**Comment by jgulledge19** [comment]
[[!churchEventsCalendar? &calendarID=`1` &categoryID=`1` ]]

Use calAdminFilterTpl for the Chunk you want to have for admin only.  So like this:

[[!churchEventsCalendar? 
  &calendarID=`1` 
  &categoryID=`1` 
  &calAdminFilterTpl=`MyAdminFilterChunk`
]]
