### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by ratpuddle** [jgulledge19/Church-Events-Calendar#5]
Hi,

I have changed the date to be %d/%m/%Y in system settings but this does not effect the js datepicker. Can the date picker be turned off or is there an easy way to change the date format for datepicker?

Cheers Adam

**Comment by ratpuddle** [comment]
Hi,

There is something else that I don't think this is an issue/request just me missing something obvious. I don't seem to be able to find a way to change the email response when a submitted event is approved. It just says Default Subject / Default Message.

I have checked the chunks but can't find a template for this email.

By the way, I love this extra it is almost exactly what I needed on my intranet.

Cheers Adam

**Comment by momon** [comment]
To adjust the date format on the datepicker find template: ChurchEvents_EventFormHeadTpl

Here look for a line that starts with:

// Datepicker
        $('#txt_public_start').datepicker({

Here you can setup the date format using:

,dateFormat: 'yy-mm-dd'

Ideally you don't want to change in this chunk since it will get recreated on updates.  You want to duplicate it instead and do it on your own chunk.

Hope that helps.

**Comment by ratpuddle** [comment]
Cheers Momon, thatwas exactly what I needed don't know how I missed that, I had even already taken a copy of that chunk and made some changes :(  I don't suppose you could help me with the other easy thing I am missing (mentioned above), I can't find where to change the Default Message that is emailed once an event is approved.

Regarding the issue I raised could I suggest that the datepicker checks the date format choosen in System Settings or the be details added to the documentation that the you also need to amend the date in the chunk.

**Comment by momon** [comment]
In my own customizations I have not yet gone as far as adjusting email templates so I'm not yet sure where those might be.  If I come across where those are I will update this and let you know, but if it isn't in a chunk, then it most likely is in the lexicon files (assuming the author built this using lexicons).  These would be within: /core/components/nameofthesnippet/lexicons.

Still if I come across it I will let you know.

**Comment by jgulledge19** [comment]
I have created the JS dateformat to work when you set/change the system settings. 

As for the subject, yes it is in the lexicons.  Go to System->Lexicon Management then select churchevents and look through them and you will see lots of choices.
